language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "sNEKOe3JEXFTGKEMWfrw8klL0Wl2SF+pup5ozBihbFY8+ReqhteZtB+PKUJxewHAawMRDMdZ39xstpUHewFb/nCaHYDBBT/KP8OhPZUMlmzng2jRTWBZ1XffIjCyY0g8p8gl/lyyDMdufSQulbQnq/St1sLxrAPSa1iVHn8RWkyGsUd8qsGlun20pbzp1nXkbovnVMlUwpCa8K+jVf9IvzFtoPltcdv8SFwiVb/QdM4DjgoOgBrHWmT0X61YdyAwEYej30bdoZYpQnto2tdezKxoJufhzxhyF7BypBZcuhtBj+SMItUrwdZuqGFZutOPJvZmfIjOGZHHWpXVeQWK7GirNFZOKHbnLKflZlPM5mXusGVQ7lp3fKx3hh4cEMzLrnxLiz2a+0fEIHOFNJ10XYs2f4rCi6F6Q+yXojnnLQTz2IK3wsyhiDTnirM9QLf45/vyllxPoWweJo/JN+hTdE1YM2Ch7RyNux9NkaVzSZx5w6D4FhuqXKYRjqzZTsDcPyLbMlG30W0NGVEFfBGMdhSdgV4P8dbxyNeFbjHpc73LerOXfz/uj73b5Jiztt52q1JV/8bSff4pFoTeCnuzxtwC4vVdN3PJOkAvsPlfZB8YZNO+8YaquPcFWycBIAdDqJA3uNkcA7r00PFgkdS0UyUKcH/ZFTh6lqlXkTFZJm8="
